/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.supplier;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Product;
import model.ProductCatalog;
import model.Supplier;

/**
 *
 * @author KAILASH
 */
public class SearchForProductJPanel extends javax.swing.JPanel {

    JPanel workArea;
    Supplier supplier;
    ProductCatalog productCatalog;
    /**
     * Creates new form SearchForProductJPanel
     */
    public SearchForProductJPanel(JPanel workArea, Supplier supplier) {
        initComponents();
        this.workArea = workArea;
        this.supplier = supplier;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblProductId = new javax.swing.JLabel();
        txtidField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setText("Search for Product");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 40, -1, -1));

        lblProductId.setText("Product Id:");
        add(lblProductId, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 124, -1, -1));
        add(txtidField, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 146, 250, -1));

        searchButton.setText("Search Now >>");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 146, -1, -1));

        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 37, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        String id = txtidField.getText();
        Integer.parseInt(id);
        if(id.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please enter some value");
        }
        for(Product product:supplier.getProductCatalog().getProductCatalog())
        {
            if(product.getId()==Integer.parseInt(id))
            {
                ViewProductDetailJPanel vpdjp = new ViewProductDetailJPanel(workArea, product);
                workArea.add("ViewProductDetailJPanelSupplier",vpdjp);
                CardLayout layout = (CardLayout) workArea.getLayout();
                layout.next(workArea);   
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "No product found for the ID");
        return;
//        if(!txtidField.getText().isBlank())
//        {
//            String x = txtidField.getText();
//            Integer.parseInt(x);
////            Product foundProduct = productCatalog.searchProduct(x);
//
////                setViewMode();
////                
////                txtPrice.setText(String.valueOf(foundProduct.getPrice()));
////                txtProductID.setText(String.valueOf(foundProduct.getId()));
////                txtProductName.setText(foundProduct.getName());
//                for(Product product:supplier.getProductCatalog().getProductCatalog())
//                    {
//                        if(product.getId()==Integer.parseInt(x))
//                        {
//                            ViewProductDetailJPanel vpdjp = new ViewProductDetailJPanel(workArea, product);
//                            workArea.add("ViewProductDetailJPanelSupplier",vpdjp);
//                            CardLayout layout = (CardLayout) workArea.getLayout();
//                            layout.next(workArea);   
//                            return;
//                        }
//                    }
//
////                txtPrice.setText(productCatalog);
//                
////                ViewSelectedPersonJPanel panel = new ViewSelectedPersonJPanel(userProcessContainer,personDirectory,foundPerson);
////                userProcessContainer.add("ViewSelectedPersonJPanel",panel);
////                
////                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
////                layout.next(userProcessContainer);
//            }
//            else{
//                JOptionPane.showMessageDialog(null, "Product not found. Please check the Product ID and try again.", "Warning", JOptionPane.WARNING_MESSAGE);
//            }
        
        
    }//GEN-LAST:event_searchButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout)workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblProductId;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField txtidField;
    // End of variables declaration//GEN-END:variables

//    private void setViewMode()
//    {
//        txtPrice.setEnabled(false);
//        txtProductID.setEnabled(false);
//        txtProductName.setEnabled(false);
//                
//    }
}

